### ISSUE TITLE
Tests fail with R# 10 SDK

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/AgentMulder#84]
```
SetUp : JetBrains.TestFramework.Utils.TestLoggerListener+TestWrapperException : 2 exceptions were thrown.
#1: Failed to read assembly metadata when adding its parts to the catalog. This Master Assembly Binder does not know how to load the assembly. Parameter name: assembly Actual value was JetBrains.ReSharper.TaskRunner.CLR45.x64, Version=104.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325.

--- EXCEPTION #1/3 [ArgumentOutOfRangeException]
Message = “This Master Assembly Binder does not know how to load the assembly.”
ExceptionPath = Root.InnerException.InnerException
ClassName = System.ArgumentOutOfRangeException
HResult = COR_E_ARGUMENTOUTOFRANGE=80131502
Source = JetBrains.Platform.Util
ParamName = assembly
ActualValue = “JetBrains.ReSharper.TaskRunner.CLR45.x64, Version=104.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
StackTraceString = “
  at JetBrains.Util.OnError.<.cctor>b__18(Exception ex)
     at JetBrains.Application.Bindings.AssemblyBinderExtensions.BindToMetadataAssembly(IAssemblyMasterBinder thіs, AssemblyNameInfo assembly, MetadataLoader loader, OnError onerror)
     at JetBrains.Application.Table.Emit.EmitCatalogTables.Assemblies.PreCreateAssemblyForCataloging(AssemblyNameInfo assnameAsRequested, EmitTimeTables tables, IAssemblyMasterBinder masterbinder, MetadataLoader metaloader)
     at JetBrains.Application.Table.Emit.EmitCatalogTables.<>c__DisplayClass3.<CreateCatalogTablesWithMetadataReader>b__0(Lifetime lifetime)
”

--- Outer ---

--- EXCEPTION #2/3 [InvalidOperationException]
Message = “Failed to read assembly metadata when adding its parts to the catalog.”
ExceptionPath = Root.InnerException
ClassName = System.InvalidOperationException
Data.Assembly = “JetBrains.ReSharper.TaskRunner.CLR45.x64, Version=104.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
InnerException = “Exception #1 at Root.InnerException.InnerException”
HResult = COR_E_INVALIDOPERATION=80131509

--- Outer ---

--- EXCEPTION #3/3 [LoggerException]
Message = “Failed to read assembly metadata when adding its parts to the catalog.”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #2 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.ILoggerEx.Error(ILogger this, Exception exception, ExceptionOrigin origin, String comment)
     at JetBrains.Application.Table.Emit.EmitCatalogTables.<>c__DisplayClass3.<CreateCatalogTablesWithMetadataReader>b__0(Lifetime lifetime)
     at JetBrains.DataFlow.Lifetimes.Using(Action`1 λ)
     at JetBrains.Application.Table.Emit.EmitCatalogTables.CreateCatalogTablesWithMetadataReader(IEnumerable`1 assemblies, IAssemblyMasterBinder masterbinder, ICollection`1 traitcalc, Stream output, OnError onerrorForMetadataLoaderTmp)
     at JetBrains.Application.BuildScript.Application.Catalogs.PartCatalogs.CreateWithMetadataReader(Lifetime lifetime, IEnumerable`1 assemblies, IAssemblyMasterBinder masterbinder)
     at JetBrains.Application.Environment.FullPartCatalogSet.CreateFromDiskFilesAndInstallResolver(Lifetime lifetime, ICollection`1 allassemblies, ICollection`1 extras)
     at JetBrains.Application.Environment.HostParameters.JetHostParametersCaller.GetFullPartCatalogSet(Lifetime lifetime)
     at JetBrains.Application.Environment.JetEnvironment..ctor(Lifetime lifetime, JetHostParametersCaller host)
     at JetBrains.Application.Environment.JetEnvironment.<>c__DisplayClasse.<InternalCreate>b__b()
     at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     at JetBrains.Application.Environment.JetEnvironment.InternalCreate(LifetimeDefinition lifetimeDefinition, JetHostParametersCaller host, JetEnvironment& environment)
     at JetBrains.DataFlow.Lifetime.AddBracket(Action FOpening, Action FClosing)
     at JetBrains.Application.Environment.JetEnvironment.CreateDontRun(Lifetime lifetime, JetHostParameters hostparams)
     at JetBrains.DataFlow.Lifetimes.Define(Lifetime lifetime, String id, Action`2 FAtomic, ILogger logger)
     at JetBrains.DataFlow.SequentialLifetimes.DefineNext(Action`2 FNext)
     at JetBrains.Util.Logging.Logger.Catch(Action action)
     at JetBrains.TestFramework.TestEnvironmentAssembly`1.SetUp()
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at NUnit.Core.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)
     at NUnit.Core.TestSuite.DoOneTimeSetUp(TestResult suiteResult)
     at NUnit.Core.TestSuite.RunSuite(EventListener listener, ITestFilter filter)
     at NUnit.Core.TestSuiteThread.RunTest()
     at NUnit.Core.TestThread.RunTestProc()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ThreadHelper.ThreadStart()
”

#2: Failed to read assembly metadata when adding its parts to the catalog. This Master Assembly Binder does not know how to load the assembly. Parameter name: assembly Actual value was JetBrains.ReSharper.TaskRunner.CLR45, Version=104.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325.

--- EXCEPTION #1/3 [ArgumentOutOfRangeException]
Message = “This Master Assembly Binder does not know how to load the assembly.”
ExceptionPath = Root.InnerException.InnerException
ClassName = System.ArgumentOutOfRangeException
HResult = COR_E_ARGUMENTOUTOFRANGE=80131502
Source = JetBrains.Platform.Util
ParamName = assembly
ActualValue = “JetBrains.ReSharper.TaskRunner.CLR45, Version=104.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
StackTraceString = “
  at JetBrains.Util.OnError.<.cctor>b__18(Exception ex)
     at JetBrains.Application.Bindings.AssemblyBinderExtensions.BindToMetadataAssembly(IAssemblyMasterBinder thіs, AssemblyNameInfo assembly, MetadataLoader loader, OnError onerror)
     at JetBrains.Application.Table.Emit.EmitCatalogTables.Assemblies.PreCreateAssemblyForCataloging(AssemblyNameInfo assnameAsRequested, EmitTimeTables tables, IAssemblyMasterBinder masterbinder, MetadataLoader metaloader)
     at JetBrains.Application.Table.Emit.EmitCatalogTables.<>c__DisplayClass3.<CreateCatalogTablesWithMetadataReader>b__0(Lifetime lifetime)
”

--- Outer ---

--- EXCEPTION #2/3 [InvalidOperationException]
Message = “Failed to read assembly metadata when adding its parts to the catalog.”
ExceptionPath = Root.InnerException
ClassName = System.InvalidOperationException
Data.Assembly = “JetBrains.ReSharper.TaskRunner.CLR45, Version=104.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
InnerException = “Exception #1 at Root.InnerException.InnerException”
HResult = COR_E_INVALIDOPERATION=80131509

--- Outer ---

--- EXCEPTION #3/3 [LoggerException]
Message = “Failed to read assembly metadata when adding its parts to the catalog.”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #2 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.ILoggerEx.Error(ILogger this, Exception exception, ExceptionOrigin origin, String comment)
     at JetBrains.Application.Table.Emit.EmitCatalogTables.<>c__DisplayClass3.<CreateCatalogTablesWithMetadataReader>b__0(Lifetime lifetime)
     at JetBrains.DataFlow.Lifetimes.Using(Action`1 λ)
     at JetBrains.Application.Table.Emit.EmitCatalogTables.CreateCatalogTablesWithMetadataReader(IEnumerable`1 assemblies, IAssemblyMasterBinder masterbinder, ICollection`1 traitcalc, Stream output, OnError onerrorForMetadataLoaderTmp)
     at JetBrains.Application.BuildScript.Application.Catalogs.PartCatalogs.CreateWithMetadataReader(Lifetime lifetime, IEnumerable`1 assemblies, IAssemblyMasterBinder masterbinder)
     at JetBrains.Application.Environment.FullPartCatalogSet.CreateFromDiskFilesAndInstallResolver(Lifetime lifetime, ICollection`1 allassemblies, ICollection`1 extras)
     at JetBrains.Application.Environment.HostParameters.JetHostParametersCaller.GetFullPartCatalogSet(Lifetime lifetime)
     at JetBrains.Application.Environment.JetEnvironment..ctor(Lifetime lifetime, JetHostParametersCaller host)
     at JetBrains.Application.Environment.JetEnvironment.<>c__DisplayClasse.<InternalCreate>b__b()
     at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     at JetBrains.Application.Environment.JetEnvironment.InternalCreate(LifetimeDefinition lifetimeDefinition, JetHostParametersCaller host, JetEnvironment& environment)
     at JetBrains.DataFlow.Lifetime.AddBracket(Action FOpening, Action FClosing)
     at JetBrains.Application.Environment.JetEnvironment.CreateDontRun(Lifetime lifetime, JetHostParameters hostparams)
     at JetBrains.DataFlow.Lifetimes.Define(Lifetime lifetime, String id, Action`2 FAtomic, ILogger logger)
     at JetBrains.DataFlow.SequentialLifetimes.DefineNext(Action`2 FNext)
     at JetBrains.Util.Logging.Logger.Catch(Action action)
     at JetBrains.TestFramework.TestEnvironmentAssembly`1.SetUp()
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at NUnit.Core.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)
     at NUnit.Core.TestSuite.DoOneTimeSetUp(TestResult suiteResult)
     at NUnit.Core.TestSuite.RunSuite(EventListener listener, ITestFilter filter)
     at NUnit.Core.TestSuiteThread.RunTest()
     at NUnit.Core.TestThread.RunTestProc()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ThreadHelper.ThreadStart()
”


   at JetBrains.Util.Tests.ThrowsAccumulatedLoggerExceptions.ThrowLoggedExceptions()
   at JetBrains.TestFramework.TestEnvironmentAssembly`1.SetUp()

```

@sirduck, @citizenmatt, any ideas?

**Comment by citizenmatt** [comment]
.net 4.5 and 32 bit.

**Comment by hmemcpy** [comment]
As in, try run it in .net 4.5 and 32 bit?

**Comment by citizenmatt** [comment]
Yep. Best I could answer on my phone on my way out :)

Did it work?

**Comment by hmemcpy** [comment]
Guess :)

**Comment by citizenmatt** [comment]
Well, seeing that I had this exact same exception message and fixed it with .net 4.5 and 32 bit, I'd say the answer is "yes" :laughing:
